const head = require("./head.js");
const content = require("./content.js");
const footer = require("./footer.js");
import icon from "../封面.jpg";
import "../css/index.css";
// import "../less/index.less";
// import "../sass/index.scss";
head.addHead();
content.addContent();
let oImg = document.createElement("img");
oImg.src = icon;
// console.log(icon);
oImg.className = "size";
document.body.appendChild(oImg);
footer.addFooter();